### ISSUE TITLE
[Feature Request] fastdom TypeScript definitions

### ISSUE THREAD

**Issue by oppianmatt** [wilsonpage/fastdom#104]
Well not really a feature but would be nice to have TypeScript definitions for those who use TypeScript to generate their Javascript.

https://github.com/DefinitelyTyped/DefinitelyTyped

Couldn't find one for fastdom. Does one exist?

**Comment by wilsonpage** [comment]
I don't know anything about TypeScript or what is required to create a 'definition'. Happy to accept a PR though :)

**Comment by oppianmatt** [comment]
Yep will do once I figure out how to. Unless someone else beats me to it...
