### ISSUE TITLE
fastdom-strict does not support context

### ISSUE THREAD

**Issue by Melatonin64** [wilsonpage/fastdom#108]
With *fastdom-strict*, 2nd argument to measure/mutate is ignored (the callback will be invoked with an `undefined` context).

**Comment by wilsonpage** [comment]
Thanks. You're right, the actual given `task()` is not being called with the given `ctx`.

https://github.com/wilsonpage/fastdom/blob/master/src/fastdom-strict.js#L23-L26

This should be an easy patch, but I don't have the time to look into it at the moment, happy to accept PRs.

**Comment by Melatonin64** [comment]
Ok, I'll try to get to it over the weekend and send a PR.
