### ISSUE TITLE
Perf issue when using in loop to get width/height & set to other element

### ISSUE THREAD

**Issue by manikantag** [wilsonpage/fastdom#114]
Hi, 

Currently I'm working on a custom CSS rendering engine for a specific need and I'll be querying `offsetHeight`/`offsetWidth` frequently and will be setting `style.height`/`style.width` and other `style` properties of elements. I'm thinking to use fastdome to see if I can get any perf benefits, but it seems other way.

I've created gist with and without fastdom: https://gist.github.com/manikantag/630288fb67453bb88c2493f8bd46aadd
(Note: I'm using **fastdom-promisified** with `async/await`).

*Use below links to preview directly:*

With fastdom: https://gist.githack.com/manikantag/630288fb67453bb88c2493f8bd46aadd/raw/fastdom-async.html

![image](https://user-images.githubusercontent.com/317299/52779742-c881db00-306e-11e9-86be-1a9fc09099e1.png)

Without fastdom: https://gist.githack.com/manikantag/630288fb67453bb88c2493f8bd46aadd/raw/no-fastdom-test.html

![image](https://user-images.githubusercontent.com/317299/52779804-e51e1300-306e-11e9-9b6f-fb8c89ab93d6.png)

When using fastdom, I'm seeing several callstacks in Chrome performance audit, which is not seen when not using fastdom.

Am I missing anything here? I expected completely opposite behavior!

**Comment by manikantag** [comment]
Ok. I think `async/await` is the culprit here. I've tried with just callbacks and Promises. Both of them are way better than `async/await` (while callback version performed little better than Promise version)

Callback version: https://gistcdn.githack.com/manikantag/630288fb67453bb88c2493f8bd46aadd/raw/db4082561ecd7e6aeff093b87efad9f19e301069/fastdom-callbacks.html

![image](https://user-images.githubusercontent.com/317299/52781737-51027a80-3073-11e9-8c59-8c81ffc1a2ae.png)


Promise version: https://gistcdn.githack.com/manikantag/630288fb67453bb88c2493f8bd46aadd/raw/db4082561ecd7e6aeff093b87efad9f19e301069/fastdom-promise.html

![image](https://user-images.githubusercontent.com/317299/52781777-6ecfdf80-3073-11e9-8015-22fd41368d1f.png)

**Comment by wilsonpage** [comment]
IIRC I wouldn't advise using Promises with Fastdom as it introduces another
layer of timing complexity. With callbacks we know when the task will be
run (or at least called). But I'm fuzzy on this, browser engines evolve and
I may not be completely up to speed :-/

**Comment by manikantag** [comment]
Thanks for confirming about Promise part. 

I still see the code without fastdom is performing (little) better. Is this because my example is a trivial one? Are there any specific real-world-scenarios where fastdom will benefit my usecase?

**Comment by wilsonpage** [comment]
I originally wrote fastdom to allow 'black box' UI components to read/write to the global dom without clashing via a shared scheduling layer (fastdom). If you are in full control of your code and don't need to share the space with third-parties/black-boxes, then you will probably squeeze better perf by rolling your own bespoke solution.

**Comment by manikantag** [comment]
That classifies better. Thanks @wilsonpage

**Comment by manikantag** [comment]
@wilsonpage Excuse me for my bad repro page. The tests I've done all WRONG. I'm just reading the `offsetHeight`/'offsetWidth` only once and using them for all the 1000 elements created in the loop. 

I've created new test pages which both reads and sets the DOM props in loop, which is the general scenario in most cases. And I can clearly see the benefits of fastdom.

**Without fastdom (correct test)**: https://gist.githack.com/manikantag/630288fb67453bb88c2493f8bd46aadd/raw/no-fastdom-correct-test.html
![image](https://user-images.githubusercontent.com/317299/52838049-4699bc80-3117-11e9-81ec-c1d8b4312510.png)


**With fastdom (correct test)**: https://gist.githack.com/manikantag/630288fb67453bb88c2493f8bd46aadd/raw/fastdom-callbacks-correct-test.html
![image](https://user-images.githubusercontent.com/317299/52838077-63ce8b00-3117-11e9-8533-fdf1b1a5251b.png)

**fastdom is clearly the WINNER. It has brought down the Rendering from 233ms to just 30ms. EXCELLENT!**

Again, excuse me for my bad tests and confusing you :) Thanks again for excellent work.

**Comment by aFarkas** [comment]
@manikantag 

Just some note on your promisified example. It is basically "slow" because you wait inside the mutation loop for each element to be added before you queue the next dom change. At this time fastdom things your already outside the executed DOM change queue and queues your DOM change for the next one. This means every element is added in another rAF and not the same rAF.

The following two examples are simply not equal.

```js
for (let i = 0; i < 10; i++) {
    // every queue is immediately processed
    readPromise().then(() => {
        // read
    });

    writePromise().then(() => {
        // write
    });
}

for (let i = 0; i < 10; i++) {
    // if i = 1 the readPromise waits for writePromise of i = 0 to be finished before executed.
    await readPromise();
    // read

    await writePromise();
    // write
}
```

So the main problem of your first example is not that you are using promises but that your `async`/`await` construct is not executed in the way you wanted to write your code in the first place.

**Comment by manikantag** [comment]
@aFarkas You are correct. Thanks for pointing that.
