### ISSUE TITLE
Releases update

### ISSUE THREAD

**Issue by drzraf** [wilsonpage/fastdom#130]
Seems like the last one is 1.0.4 and the compiled code has been updated in 4 years.
I fear that while https://cdnjs.com/libraries/fastdom provide 1.0.10 (based on package.json), the file actually provided is the old one.

Do you mind refreshing bundles?

**Comment by wilsonpage** [comment]
I've just pushed a commit with an updated `fastdom.min.js` and stamped a new package version.
