### ISSUE TITLE
fastdom.nextJob?

### ISSUE THREAD

**Issue by alekseykulikov** [wilsonpage/fastdom#38]
Hi @wilsonpage, thank you for the library! I have played with it a little bit, and wish to have one really helpful method:

```js
/**
 * Schedule fastdom read/write operation.
 * Also passes additional `args` to `cb` to perform short forms like:
 *
 *    nextJob(activate.card, app.get('cardId'));
 */

function nextJob(cb) {
  var args = slice.call(arguments, 1);

  fastdom.write(function() {
    fastdom.read(function() { cb.apply(null, args) });
  });
}
```

It basically adds callback to read/write queue. It's really useful when you write tests, or need to perform something, after fastdom operations done. It will help to avoid callbacks support, because fastdom already has their scheduler, and you can say exactly, when all read/writes done.

**Comment by wilsonpage** [comment]
A promise API is not available as an [extension](https://github.com/wilsonpage/fastdom#extensions). Feedback appreciated :)
