### ISSUE TITLE
[Please help] Whats FastDom?

### ISSUE THREAD

**Issue by dalisoft** [wilsonpage/fastdom#61]
Hi all, i have some question.
1. FastDom optimizes Chrome Timeline (aka FPS)?
2. How to use this in animation engine?
3. This is optimizes my animation fps?

**Comment by wilsonpage** [comment]
FastDom schedules your DOM read and write operations to help prevent layout thrashing. If you want to find out more about layout thrashing, I wrote a more [detailed article](http://wilsonpage.co.uk/preventing-layout-thrashing/) on it :)
