### ISSUE TITLE
Any plans to Promise based API? 

### ISSUE THREAD

**Issue by ColCh** [wilsonpage/fastdom#62]

**Comment by wilsonpage** [comment]
Try out the [`v1-beta`](https://github.com/wilsonpage/fastdom/tree/v1-beta) branch. It introduces the concept of 'extensions'. FastDom will ship with a couple of 'core' extensions, one of which is [`fastdom-promised`](https://github.com/wilsonpage/fastdom/blob/v1-beta/extensions/fastdom-promised.js).

You can try it out like:

```js
var myFastdom = fastdom.extend(fastdomPromised);
myFastdom.measure(...).then(...);
```

**Comment by ColCh** [comment]
I think that's enough for this issue  :)

**Comment by wilsonpage** [comment]
BTW looking for feedback on the [`v1-beta`](https://github.com/wilsonpage/fastdom/tree/v1-beta) branch before I merge. Do oyu have time to take look? :)

**Comment by ColCh** [comment]
May be...  I will be in "disabled"  state for New Year and following week :)  Happy NY BTW!

**Comment by wilsonpage** [comment]
Thank mate, no push! :)

**Comment by wilsonpage** [comment]
*rush
