### ISSUE TITLE
purpose of V-1 beta?

### ISSUE THREAD

**Issue by yairEO** [wilsonpage/fastdom#68]
The README doesn't say what is the difference between that and Master, and why was it created.

 Also, Is it safe to use in production?

**Comment by wilsonpage** [comment]
I'm working on a more refined version that drops some of the less useful APIs and adds a couple of useful things. I hardly have any spare itme to work on this, so progress is slow.

I'd love for you to try it out and give some feedback :)

**Comment by magnumjs** [comment]
How about a way to limit the frame rate? I'd like to not have a higher refresh rate than 30 fps.

**Comment by paulirish** [comment]
> How about a way to limit the frame rate? I'd like to not have a higher refresh rate than 30 fps.

That's out of scope for this library. There are other libraries that can throttle your writes to every 33ms
