### ISSUE TITLE
Make FastDOM available on a CDN

### ISSUE THREAD

**Issue by j1r** [wilsonpage/fastdom#86]
It might facilitate quick prototyping and maybe lightweight production deployment, too, if FastDOM was available on a 3rd party CDN (at least I couldn't find FastDOM on cdnjs.com or jsDelivr, and there's no mention of a CDN in docs). Any chance?

(There's RawGit, of course, but I'm not sure how dependable it is.)

**Comment by wilsonpage** [comment]
Good idea. I'd be up for that :)

**Comment by wilsonpage** [comment]
Requested https://github.com/cdnjs/cdnjs/issues/8499

**Comment by j1r** [comment]
Seems that inclusion in cdnjs.com can be requested by opening an issue on GitHub (sorry the link is a mess):

https://github.com/cdnjs/cdnjs/issues/new?title=%5BRequest%5D%20Add%20_library_name_%20&body=**Library%20name%3A**%20%0A**Git%20repository%20url%3A**%0A**npm%20package%20url(optional)%3A**%20%0A**License(s)%3A**%0A**Official%20homepage%3A**%0A**Wanna%20say%20something?%20Leave%20message%20here%3A**%0A%0A=====================%0ANotes%20from%20cdnjs%20maintainer%3A%0APlease%20read%20the%20README.md%20and%20CONTRIBUTING.md%20document%20first.%0A%0AYou%20are%20welcome%20to%20add%20a%20library%20via%20sending%20pull%20request%2C%0Ait%27ll%20be%20faster%20then%20just%20opening%20a%20request%20issue%2C%0Aand%20please%20don%27t%20forget%20to%20read%20the%20guidelines%20for%20contributing%2C%20thanks!!

https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#b-pull-request
https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#d-adding-a-new-library

(I don't know if a maintainer should make the inclusion request.)

**Comment by j1r** [comment]
Seems to have been added, yay!
https://github.com/cdnjs/cdnjs/issues/8499
https://github.com/cdnjs/cdnjs/pull/8507
https://cdnjs.com/libraries/fastdom
