### ISSUE TITLE
fastdom.raf is always exported as setTimeout 

### ISSUE THREAD

**Issue by tmpst** [wilsonpage/fastdom#88]
When required in browserify the value of `win` passed into the closure is an empty object, not `window`, thus fastdom.raf is implemented as setTimeout rather than requestAnimationFrame.

I've put a test case here: http://requirebin.com/?gist=tmpst/7d38bf287739be7d661be0f97fd83440

**Comment by wilsonpage** [comment]
Wow this is a great catch! I always though `this === window` in Browserify!

Much appreciated Sir.

**Comment by wilsonpage** [comment]
Fixed by https://github.com/wilsonpage/fastdom/commit/5614caa7cb6577810f836bb532098581f1283e42
